"""Auto migration

Revision ID: 0eb6892a5a99
Revises: b8e1bc2d08b7
Create Date: 2024-10-13 14:39:14.513369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb6892a5a99'
down_revision = 'b8e1bc2d08b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
