"""empty message

Revision ID: 3d0a92f01dfd
Revises: 
Create Date: 2024-10-07 03:26:01.066120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d0a92f01dfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    op.drop_table('points')
    op.drop_table('products')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('products_id_seq'::regclass)"),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
                    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='products_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('points',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='points_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='points_pkey'),
                    sa.UniqueConstraint('user_id', name='points_user_id_key')
                    )
    op.create_table('orders',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('orders_id_seq'::regclass)"),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('order_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='orders_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='orders_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('order_items',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_items_order_id_fkey'),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='order_items_product_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='order_items_pkey')
                    )
    op.create_table('users',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
                    sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='users_pkey')
                    )
    # ### end Alembic commands ###
