"""Auto migration

Revision ID: 4249ccc0db8f
Revises: 85786d1ffdbd
Create Date: 2024-10-15 07:02:08.222741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4249ccc0db8f'
down_revision = '85786d1ffdbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('images',
               existing_type=postgresql.BYTEA(),
               nullable=False)
        batch_op.drop_constraint('item_description_key', type_='unique')
        batch_op.drop_constraint('item_features_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_unique_constraint('item_features_key', ['features'])
        batch_op.create_unique_constraint('item_description_key', ['description'])
        batch_op.alter_column('images',
               existing_type=postgresql.BYTEA(),
               nullable=True)

    # ### end Alembic commands ###
