"""Auto migration

Revision ID: 727e8435afe9
Revises: ac731acb08f6
Create Date: 2024-10-07 05:28:12.106047

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '727e8435afe9'
down_revision = 'ac731acb08f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_id', new_column_name='id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id', new_column_name='user_id')

    # ### end Alembic commands ###
