"""Auto migration

Revision ID: 85786d1ffdbd
Revises: ff773e525789
Create Date: 2024-10-15 06:50:13.890529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85786d1ffdbd'
down_revision = 'ff773e525789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=1200), nullable=False),
    sa.Column('features', sa.String(length=1200), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('images', sa.PickleType(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('features'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    # ### end Alembic commands ###
